# Generated by Django 6.0.1 on 2026-01-17 17:25

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#     ]

#     operations = [
#     ]

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    dependencies = [] # This should be empty for the first migration
    operations = [
        VectorExtension()
    ]
