# Generated by Django 5.2.11 on 2026-02-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_knowledgebase_options_knowledgebase_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_files/'),
        ),
        migrations.AlterField(
            model_name='botconfiguration',
            name='system_prompt',
            field=models.TextField(default='You are a professional support assistant for {company_name}. Use ONLY the provided context to answer customer questions. If the answer is not in the context, politely say you do not know. Be brief, helpful, and professional.'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='text', max_length=10),
        ),
    ]
