# Generated by Django 4.2.11 on 2026-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_knowledgebase_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationhistory',
            name='call_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='conversation_type',
            field=models.CharField(choices=[('chatbot', 'Chatbot'), ('voicebot', 'Voicebot'), ('voicecall', 'Voice Call')], default='chatbot', max_length=20),
        ),
    ]
